/* soapServer.c
   Generated by gSOAP 2.8.10 from ims.h

Copyright(C) 2000-2012, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
1) GPL or 2) Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"
#ifdef __cplusplus
extern "C" {
#endif

SOAP_SOURCE_STAMP("@(#) soapServer.c ver 2.8.10 2013-12-04 18:41:29 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap *soap)
{
#ifndef WITH_FASTCGI
	unsigned int k = soap->max_keep_alive;
#endif
	do
	{
#ifndef WITH_FASTCGI
		if (soap->max_keep_alive > 0 && !--k)
			soap->keep_alive = 0;
#endif
		if (soap_begin_serve(soap))
		{	if (soap->error >= SOAP_STOP)
				continue;
			return soap->error;
		}
		if (soap_serve_request(soap) || (soap->fserveloop && soap->fserveloop(soap)))
		{
#ifdef WITH_FASTCGI
			soap_send_fault(soap);
#else
			return soap_send_fault(soap);
#endif
		}

#ifdef WITH_FASTCGI
		soap_destroy(soap);
		soap_end(soap);
	} while (1);
#else
	} while (soap->keep_alive);
#endif
	return SOAP_OK;
}

#ifndef WITH_NOSERVEREQUEST
SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap *soap)
{
	soap_peek_element(soap);
	if (!soap_match_tag(soap, soap->tag, "ims:login"))
		return soap_serve_ims__login(soap);
	if (!soap_match_tag(soap, soap->tag, "ims:darAltaUsuario"))
		return soap_serve_ims__darAltaUsuario(soap);
	if (!soap_match_tag(soap, soap->tag, "ims:darBajaUsuario"))
		return soap_serve_ims__darBajaUsuario(soap);
	if (!soap_match_tag(soap, soap->tag, "ims:listarAmigos"))
		return soap_serve_ims__listarAmigos(soap);
	if (!soap_match_tag(soap, soap->tag, "ims:logout"))
		return soap_serve_ims__logout(soap);
	if (!soap_match_tag(soap, soap->tag, "ims:anadirAmigo"))
		return soap_serve_ims__anadirAmigo(soap);
	if (!soap_match_tag(soap, soap->tag, "ims:tratarSolicitud"))
		return soap_serve_ims__tratarSolicitud(soap);
	if (!soap_match_tag(soap, soap->tag, "ims:listarPendientes"))
		return soap_serve_ims__listarPendientes(soap);
	if (!soap_match_tag(soap, soap->tag, "ims:enviarMensaje"))
		return soap_serve_ims__enviarMensaje(soap);
	if (!soap_match_tag(soap, soap->tag, "ims:recibirMensajes"))
		return soap_serve_ims__recibirMensajes(soap);
	if (!soap_match_tag(soap, soap->tag, "ims:mensajesRecibidos"))
		return soap_serve_ims__mensajesRecibidos(soap);
	return soap->error = SOAP_NO_METHOD;
}
#endif

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ims__login(struct soap *soap)
{	struct ims__login soap_tmp_ims__login;
	struct ims__loginResponse soap_tmp_ims__loginResponse;
	int soap_tmp_int;
	soap_default_ims__loginResponse(soap, &soap_tmp_ims__loginResponse);
	soap_default_int(soap, &soap_tmp_int);
	soap_tmp_ims__loginResponse.result = &soap_tmp_int;
	soap_default_ims__login(soap, &soap_tmp_ims__login);
	soap->encodingStyle = NULL;
	if (!soap_get_ims__login(soap, &soap_tmp_ims__login, "ims:login", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ims__login(soap, soap_tmp_ims__login.login, soap_tmp_ims__loginResponse.result);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ims__loginResponse(soap, &soap_tmp_ims__loginResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ims__loginResponse(soap, &soap_tmp_ims__loginResponse, "ims:loginResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ims__loginResponse(soap, &soap_tmp_ims__loginResponse, "ims:loginResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ims__darAltaUsuario(struct soap *soap)
{	struct ims__darAltaUsuario soap_tmp_ims__darAltaUsuario;
	struct ims__darAltaUsuarioResponse soap_tmp_ims__darAltaUsuarioResponse;
	int soap_tmp_int;
	soap_default_ims__darAltaUsuarioResponse(soap, &soap_tmp_ims__darAltaUsuarioResponse);
	soap_default_int(soap, &soap_tmp_int);
	soap_tmp_ims__darAltaUsuarioResponse.result = &soap_tmp_int;
	soap_default_ims__darAltaUsuario(soap, &soap_tmp_ims__darAltaUsuario);
	soap->encodingStyle = NULL;
	if (!soap_get_ims__darAltaUsuario(soap, &soap_tmp_ims__darAltaUsuario, "ims:darAltaUsuario", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ims__darAltaUsuario(soap, soap_tmp_ims__darAltaUsuario.login, soap_tmp_ims__darAltaUsuarioResponse.result);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ims__darAltaUsuarioResponse(soap, &soap_tmp_ims__darAltaUsuarioResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ims__darAltaUsuarioResponse(soap, &soap_tmp_ims__darAltaUsuarioResponse, "ims:darAltaUsuarioResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ims__darAltaUsuarioResponse(soap, &soap_tmp_ims__darAltaUsuarioResponse, "ims:darAltaUsuarioResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ims__darBajaUsuario(struct soap *soap)
{	struct ims__darBajaUsuario soap_tmp_ims__darBajaUsuario;
	struct ims__darBajaUsuarioResponse soap_tmp_ims__darBajaUsuarioResponse;
	int soap_tmp_int;
	soap_default_ims__darBajaUsuarioResponse(soap, &soap_tmp_ims__darBajaUsuarioResponse);
	soap_default_int(soap, &soap_tmp_int);
	soap_tmp_ims__darBajaUsuarioResponse.result = &soap_tmp_int;
	soap_default_ims__darBajaUsuario(soap, &soap_tmp_ims__darBajaUsuario);
	soap->encodingStyle = NULL;
	if (!soap_get_ims__darBajaUsuario(soap, &soap_tmp_ims__darBajaUsuario, "ims:darBajaUsuario", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ims__darBajaUsuario(soap, soap_tmp_ims__darBajaUsuario.login, soap_tmp_ims__darBajaUsuario.user, soap_tmp_ims__darBajaUsuarioResponse.result);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ims__darBajaUsuarioResponse(soap, &soap_tmp_ims__darBajaUsuarioResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ims__darBajaUsuarioResponse(soap, &soap_tmp_ims__darBajaUsuarioResponse, "ims:darBajaUsuarioResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ims__darBajaUsuarioResponse(soap, &soap_tmp_ims__darBajaUsuarioResponse, "ims:darBajaUsuarioResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ims__listarAmigos(struct soap *soap)
{	struct ims__listarAmigos soap_tmp_ims__listarAmigos;
	struct ims__listarAmigosResponse soap_tmp_ims__listarAmigosResponse;
	struct ListaUsuarios soap_tmp_ListaUsuarios;
	soap_default_ims__listarAmigosResponse(soap, &soap_tmp_ims__listarAmigosResponse);
	soap_default_ListaUsuarios(soap, &soap_tmp_ListaUsuarios);
	soap_tmp_ims__listarAmigosResponse.listaAmigos = &soap_tmp_ListaUsuarios;
	soap_default_ims__listarAmigos(soap, &soap_tmp_ims__listarAmigos);
	soap->encodingStyle = NULL;
	if (!soap_get_ims__listarAmigos(soap, &soap_tmp_ims__listarAmigos, "ims:listarAmigos", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ims__listarAmigos(soap, soap_tmp_ims__listarAmigos.login, soap_tmp_ims__listarAmigos.result, soap_tmp_ims__listarAmigosResponse.listaAmigos);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ims__listarAmigosResponse(soap, &soap_tmp_ims__listarAmigosResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ims__listarAmigosResponse(soap, &soap_tmp_ims__listarAmigosResponse, "ims:listarAmigosResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ims__listarAmigosResponse(soap, &soap_tmp_ims__listarAmigosResponse, "ims:listarAmigosResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ims__logout(struct soap *soap)
{	struct ims__logout soap_tmp_ims__logout;
	struct ims__logoutResponse soap_tmp_ims__logoutResponse;
	int soap_tmp_int;
	soap_default_ims__logoutResponse(soap, &soap_tmp_ims__logoutResponse);
	soap_default_int(soap, &soap_tmp_int);
	soap_tmp_ims__logoutResponse.result = &soap_tmp_int;
	soap_default_ims__logout(soap, &soap_tmp_ims__logout);
	soap->encodingStyle = NULL;
	if (!soap_get_ims__logout(soap, &soap_tmp_ims__logout, "ims:logout", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ims__logout(soap, soap_tmp_ims__logout.login, soap_tmp_ims__logoutResponse.result);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ims__logoutResponse(soap, &soap_tmp_ims__logoutResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ims__logoutResponse(soap, &soap_tmp_ims__logoutResponse, "ims:logoutResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ims__logoutResponse(soap, &soap_tmp_ims__logoutResponse, "ims:logoutResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ims__anadirAmigo(struct soap *soap)
{	struct ims__anadirAmigo soap_tmp_ims__anadirAmigo;
	struct ims__anadirAmigoResponse soap_tmp_ims__anadirAmigoResponse;
	int soap_tmp_int;
	soap_default_ims__anadirAmigoResponse(soap, &soap_tmp_ims__anadirAmigoResponse);
	soap_default_int(soap, &soap_tmp_int);
	soap_tmp_ims__anadirAmigoResponse.result = &soap_tmp_int;
	soap_default_ims__anadirAmigo(soap, &soap_tmp_ims__anadirAmigo);
	soap->encodingStyle = NULL;
	if (!soap_get_ims__anadirAmigo(soap, &soap_tmp_ims__anadirAmigo, "ims:anadirAmigo", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ims__anadirAmigo(soap, soap_tmp_ims__anadirAmigo.login, soap_tmp_ims__anadirAmigo.destino, soap_tmp_ims__anadirAmigoResponse.result);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ims__anadirAmigoResponse(soap, &soap_tmp_ims__anadirAmigoResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ims__anadirAmigoResponse(soap, &soap_tmp_ims__anadirAmigoResponse, "ims:anadirAmigoResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ims__anadirAmigoResponse(soap, &soap_tmp_ims__anadirAmigoResponse, "ims:anadirAmigoResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ims__tratarSolicitud(struct soap *soap)
{	struct ims__tratarSolicitud soap_tmp_ims__tratarSolicitud;
	struct ims__tratarSolicitudResponse soap_tmp_ims__tratarSolicitudResponse;
	int soap_tmp_int;
	soap_default_ims__tratarSolicitudResponse(soap, &soap_tmp_ims__tratarSolicitudResponse);
	soap_default_int(soap, &soap_tmp_int);
	soap_tmp_ims__tratarSolicitudResponse.result = &soap_tmp_int;
	soap_default_ims__tratarSolicitud(soap, &soap_tmp_ims__tratarSolicitud);
	soap->encodingStyle = NULL;
	if (!soap_get_ims__tratarSolicitud(soap, &soap_tmp_ims__tratarSolicitud, "ims:tratarSolicitud", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ims__tratarSolicitud(soap, soap_tmp_ims__tratarSolicitud.login, soap_tmp_ims__tratarSolicitud.solicitante, soap_tmp_ims__tratarSolicitudResponse.result);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ims__tratarSolicitudResponse(soap, &soap_tmp_ims__tratarSolicitudResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ims__tratarSolicitudResponse(soap, &soap_tmp_ims__tratarSolicitudResponse, "ims:tratarSolicitudResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ims__tratarSolicitudResponse(soap, &soap_tmp_ims__tratarSolicitudResponse, "ims:tratarSolicitudResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ims__listarPendientes(struct soap *soap)
{	struct ims__listarPendientes soap_tmp_ims__listarPendientes;
	struct ims__listarPendientesResponse soap_tmp_ims__listarPendientesResponse;
	struct ListaUsuarios soap_tmp_ListaUsuarios;
	soap_default_ims__listarPendientesResponse(soap, &soap_tmp_ims__listarPendientesResponse);
	soap_default_ListaUsuarios(soap, &soap_tmp_ListaUsuarios);
	soap_tmp_ims__listarPendientesResponse.listaAmigos = &soap_tmp_ListaUsuarios;
	soap_default_ims__listarPendientes(soap, &soap_tmp_ims__listarPendientes);
	soap->encodingStyle = NULL;
	if (!soap_get_ims__listarPendientes(soap, &soap_tmp_ims__listarPendientes, "ims:listarPendientes", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ims__listarPendientes(soap, soap_tmp_ims__listarPendientes.login, soap_tmp_ims__listarPendientes.result, soap_tmp_ims__listarPendientesResponse.listaAmigos);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ims__listarPendientesResponse(soap, &soap_tmp_ims__listarPendientesResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ims__listarPendientesResponse(soap, &soap_tmp_ims__listarPendientesResponse, "ims:listarPendientesResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ims__listarPendientesResponse(soap, &soap_tmp_ims__listarPendientesResponse, "ims:listarPendientesResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ims__enviarMensaje(struct soap *soap)
{	struct ims__enviarMensaje soap_tmp_ims__enviarMensaje;
	struct ims__enviarMensajeResponse soap_tmp_ims__enviarMensajeResponse;
	int soap_tmp_int;
	soap_default_ims__enviarMensajeResponse(soap, &soap_tmp_ims__enviarMensajeResponse);
	soap_default_int(soap, &soap_tmp_int);
	soap_tmp_ims__enviarMensajeResponse.resul = &soap_tmp_int;
	soap_default_ims__enviarMensaje(soap, &soap_tmp_ims__enviarMensaje);
	soap->encodingStyle = NULL;
	if (!soap_get_ims__enviarMensaje(soap, &soap_tmp_ims__enviarMensaje, "ims:enviarMensaje", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ims__enviarMensaje(soap, soap_tmp_ims__enviarMensaje.login, soap_tmp_ims__enviarMensaje.destino, soap_tmp_ims__enviarMensaje.msg, soap_tmp_ims__enviarMensajeResponse.resul);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ims__enviarMensajeResponse(soap, &soap_tmp_ims__enviarMensajeResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ims__enviarMensajeResponse(soap, &soap_tmp_ims__enviarMensajeResponse, "ims:enviarMensajeResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ims__enviarMensajeResponse(soap, &soap_tmp_ims__enviarMensajeResponse, "ims:enviarMensajeResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ims__recibirMensajes(struct soap *soap)
{	struct ims__recibirMensajes soap_tmp_ims__recibirMensajes;
	struct ims__recibirMensajesResponse soap_tmp_ims__recibirMensajesResponse;
	struct ListaMensajes soap_tmp_ListaMensajes;
	soap_default_ims__recibirMensajesResponse(soap, &soap_tmp_ims__recibirMensajesResponse);
	soap_default_ListaMensajes(soap, &soap_tmp_ListaMensajes);
	soap_tmp_ims__recibirMensajesResponse.listaMsg = &soap_tmp_ListaMensajes;
	soap_default_ims__recibirMensajes(soap, &soap_tmp_ims__recibirMensajes);
	soap->encodingStyle = NULL;
	if (!soap_get_ims__recibirMensajes(soap, &soap_tmp_ims__recibirMensajes, "ims:recibirMensajes", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ims__recibirMensajes(soap, soap_tmp_ims__recibirMensajes.login, soap_tmp_ims__recibirMensajesResponse.listaMsg);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ims__recibirMensajesResponse(soap, &soap_tmp_ims__recibirMensajesResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ims__recibirMensajesResponse(soap, &soap_tmp_ims__recibirMensajesResponse, "ims:recibirMensajesResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ims__recibirMensajesResponse(soap, &soap_tmp_ims__recibirMensajesResponse, "ims:recibirMensajesResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ims__mensajesRecibidos(struct soap *soap)
{	struct ims__mensajesRecibidos soap_tmp_ims__mensajesRecibidos;
	struct ims__mensajesRecibidosResponse soap_tmp_ims__mensajesRecibidosResponse;
	int soap_tmp_int;
	soap_default_ims__mensajesRecibidosResponse(soap, &soap_tmp_ims__mensajesRecibidosResponse);
	soap_default_int(soap, &soap_tmp_int);
	soap_tmp_ims__mensajesRecibidosResponse.result = &soap_tmp_int;
	soap_default_ims__mensajesRecibidos(soap, &soap_tmp_ims__mensajesRecibidos);
	soap->encodingStyle = NULL;
	if (!soap_get_ims__mensajesRecibidos(soap, &soap_tmp_ims__mensajesRecibidos, "ims:mensajesRecibidos", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ims__mensajesRecibidos(soap, soap_tmp_ims__mensajesRecibidos.login, soap_tmp_ims__mensajesRecibidosResponse.result);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ims__mensajesRecibidosResponse(soap, &soap_tmp_ims__mensajesRecibidosResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ims__mensajesRecibidosResponse(soap, &soap_tmp_ims__mensajesRecibidosResponse, "ims:mensajesRecibidosResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ims__mensajesRecibidosResponse(soap, &soap_tmp_ims__mensajesRecibidosResponse, "ims:mensajesRecibidosResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

#ifdef __cplusplus
}
#endif

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapServer.c */
