/* soapStub.h
   Generated by gSOAP 2.8.10 from ims.h

Copyright(C) 2000-2012, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
1) GPL or 2) Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapStub_H
#define soapStub_H
#define IMS_MAX_MSG_SIZE 256
#include "stdsoap2.h"
#if GSOAP_VERSION != 20810
# error "GSOAP VERSION MISMATCH IN GENERATED CODE: PLEASE REINSTALL PACKAGE"
#endif

#ifdef __cplusplus
extern "C" {
#endif

/******************************************************************************\
 *                                                                            *
 * Enumerations                                                               *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Types with Custom Serializers                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Classes and Structs                                                        *
 *                                                                            *
\******************************************************************************/


#if 0 /* volatile type: do not declare here, declared elsewhere */

#endif

#ifndef SOAP_TYPE_Message
#define SOAP_TYPE_Message (8)
/* Message */
struct Message
{
	char name[20];	/* required element of type Array20Ofbyte */
	char msg[144];	/* required element of type Array144Ofbyte */
};
#endif

#ifndef SOAP_TYPE_User
#define SOAP_TYPE_User (11)
/* User */
struct User
{
	char login[20];	/* required element of type Array20Ofbyte */
	int estado;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ListaUsuarios
#define SOAP_TYPE_ListaUsuarios (12)
/* ListaUsuarios */
struct ListaUsuarios
{
	struct User listaUsuarios[50];	/* required element of type Array50OfUser */
	int contador;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ListaMensajes
#define SOAP_TYPE_ListaMensajes (14)
/* ListaMensajes */
struct ListaMensajes
{
	struct Message mensajes[100];	/* required element of type Array100OfMessage */
	int numMensajes;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ims__loginResponse
#define SOAP_TYPE_ims__loginResponse (18)
/* ims:loginResponse */
struct ims__loginResponse
{
	int *result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ims__login
#define SOAP_TYPE_ims__login (19)
/* ims:login */
struct ims__login
{
	char *login;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ims__darAltaUsuarioResponse
#define SOAP_TYPE_ims__darAltaUsuarioResponse (21)
/* ims:darAltaUsuarioResponse */
struct ims__darAltaUsuarioResponse
{
	int *result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ims__darAltaUsuario
#define SOAP_TYPE_ims__darAltaUsuario (22)
/* ims:darAltaUsuario */
struct ims__darAltaUsuario
{
	char *login;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ims__darBajaUsuarioResponse
#define SOAP_TYPE_ims__darBajaUsuarioResponse (24)
/* ims:darBajaUsuarioResponse */
struct ims__darBajaUsuarioResponse
{
	int *result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ims__darBajaUsuario
#define SOAP_TYPE_ims__darBajaUsuario (25)
/* ims:darBajaUsuario */
struct ims__darBajaUsuario
{
	char *login;	/* optional element of type xsd:string */
	char *user;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ims__listarAmigosResponse
#define SOAP_TYPE_ims__listarAmigosResponse (28)
/* ims:listarAmigosResponse */
struct ims__listarAmigosResponse
{
	struct ListaUsuarios *listaAmigos;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ListaUsuarios */
};
#endif

#ifndef SOAP_TYPE_ims__listarAmigos
#define SOAP_TYPE_ims__listarAmigos (29)
/* ims:listarAmigos */
struct ims__listarAmigos
{
	char *login;	/* optional element of type xsd:string */
	int *result;	/* optional element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ims__logoutResponse
#define SOAP_TYPE_ims__logoutResponse (31)
/* ims:logoutResponse */
struct ims__logoutResponse
{
	int *result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ims__logout
#define SOAP_TYPE_ims__logout (32)
/* ims:logout */
struct ims__logout
{
	char *login;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ims__anadirAmigoResponse
#define SOAP_TYPE_ims__anadirAmigoResponse (34)
/* ims:anadirAmigoResponse */
struct ims__anadirAmigoResponse
{
	int *result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ims__anadirAmigo
#define SOAP_TYPE_ims__anadirAmigo (35)
/* ims:anadirAmigo */
struct ims__anadirAmigo
{
	char *login;	/* optional element of type xsd:string */
	char *destino;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ims__tratarSolicitudResponse
#define SOAP_TYPE_ims__tratarSolicitudResponse (37)
/* ims:tratarSolicitudResponse */
struct ims__tratarSolicitudResponse
{
	int *result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ims__tratarSolicitud
#define SOAP_TYPE_ims__tratarSolicitud (38)
/* ims:tratarSolicitud */
struct ims__tratarSolicitud
{
	char *login;	/* optional element of type xsd:string */
	char *solicitante;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ims__listarPendientesResponse
#define SOAP_TYPE_ims__listarPendientesResponse (40)
/* ims:listarPendientesResponse */
struct ims__listarPendientesResponse
{
	struct ListaUsuarios *listaAmigos;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ListaUsuarios */
};
#endif

#ifndef SOAP_TYPE_ims__listarPendientes
#define SOAP_TYPE_ims__listarPendientes (41)
/* ims:listarPendientes */
struct ims__listarPendientes
{
	char *login;	/* optional element of type xsd:string */
	int *result;	/* optional element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ims__enviarMensajeResponse
#define SOAP_TYPE_ims__enviarMensajeResponse (43)
/* ims:enviarMensajeResponse */
struct ims__enviarMensajeResponse
{
	int *resul;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ims__enviarMensaje
#define SOAP_TYPE_ims__enviarMensaje (44)
/* ims:enviarMensaje */
struct ims__enviarMensaje
{
	char *login;	/* optional element of type xsd:string */
	char *destino;	/* optional element of type xsd:string */
	char *msg;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ims__recibirMensajesResponse
#define SOAP_TYPE_ims__recibirMensajesResponse (47)
/* ims:recibirMensajesResponse */
struct ims__recibirMensajesResponse
{
	struct ListaMensajes *listaMsg;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ListaMensajes */
};
#endif

#ifndef SOAP_TYPE_ims__recibirMensajes
#define SOAP_TYPE_ims__recibirMensajes (48)
/* ims:recibirMensajes */
struct ims__recibirMensajes
{
	char *login;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ims__mensajesRecibidosResponse
#define SOAP_TYPE_ims__mensajesRecibidosResponse (50)
/* ims:mensajesRecibidosResponse */
struct ims__mensajesRecibidosResponse
{
	int *result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ims__mensajesRecibidos
#define SOAP_TYPE_ims__mensajesRecibidos (51)
/* ims:mensajesRecibidos */
struct ims__mensajesRecibidos
{
	char *login;	/* optional element of type xsd:string */
};
#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (52)
/* SOAP Header: */
struct SOAP_ENV__Header
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (53)
/* SOAP Fault Code: */
struct SOAP_ENV__Code
{
	char *SOAP_ENV__Value;	/* optional element of type xsd:QName */
	struct SOAP_ENV__Code *SOAP_ENV__Subcode;	/* optional element of type SOAP-ENV:Code */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (55)
/* SOAP-ENV:Detail */
struct SOAP_ENV__Detail
{
	char *__any;
	int __type;	/* any type of element <fault> (defined below) */
	void *fault;	/* transient */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (58)
/* SOAP-ENV:Reason */
struct SOAP_ENV__Reason
{
	char *SOAP_ENV__Text;	/* optional element of type xsd:string */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (59)
/* SOAP Fault: */
struct SOAP_ENV__Fault
{
	char *faultcode;	/* optional element of type xsd:QName */
	char *faultstring;	/* optional element of type xsd:string */
	char *faultactor;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *detail;	/* optional element of type SOAP-ENV:Detail */
	struct SOAP_ENV__Code *SOAP_ENV__Code;	/* optional element of type SOAP-ENV:Code */
	struct SOAP_ENV__Reason *SOAP_ENV__Reason;	/* optional element of type SOAP-ENV:Reason */
	char *SOAP_ENV__Node;	/* optional element of type xsd:string */
	char *SOAP_ENV__Role;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *SOAP_ENV__Detail;	/* optional element of type SOAP-ENV:Detail */
};
#endif

#endif

/******************************************************************************\
 *                                                                            *
 * Typedefs                                                                   *
 *                                                                            *
\******************************************************************************/

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
typedef char *_QName;
#endif

#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (6)
typedef char *_XML;
#endif

#ifndef SOAP_TYPE_xsd__string
#define SOAP_TYPE_xsd__string (7)
typedef char *xsd__string;
#endif


/******************************************************************************\
 *                                                                            *
 * Externals                                                                  *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Server-Side Operations                                                     *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 ims__login(struct soap*, char *login, int *result);

SOAP_FMAC5 int SOAP_FMAC6 ims__darAltaUsuario(struct soap*, char *login, int *result);

SOAP_FMAC5 int SOAP_FMAC6 ims__darBajaUsuario(struct soap*, char *login, char *user, int *result);

SOAP_FMAC5 int SOAP_FMAC6 ims__listarAmigos(struct soap*, char *login, int *result, struct ListaUsuarios *listaAmigos);

SOAP_FMAC5 int SOAP_FMAC6 ims__logout(struct soap*, char *login, int *result);

SOAP_FMAC5 int SOAP_FMAC6 ims__anadirAmigo(struct soap*, char *login, char *destino, int *result);

SOAP_FMAC5 int SOAP_FMAC6 ims__tratarSolicitud(struct soap*, char *login, char *solicitante, int *result);

SOAP_FMAC5 int SOAP_FMAC6 ims__listarPendientes(struct soap*, char *login, int *result, struct ListaUsuarios *listaAmigos);

SOAP_FMAC5 int SOAP_FMAC6 ims__enviarMensaje(struct soap*, char *login, char *destino, char *msg, int *resul);

SOAP_FMAC5 int SOAP_FMAC6 ims__recibirMensajes(struct soap*, char *login, struct ListaMensajes *listaMsg);

SOAP_FMAC5 int SOAP_FMAC6 ims__mensajesRecibidos(struct soap*, char *login, int *result);

/******************************************************************************\
 *                                                                            *
 * Server-Side Skeletons to Invoke Service Operations                         *
 *                                                                            *
\******************************************************************************/

SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ims__login(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ims__darAltaUsuario(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ims__darBajaUsuario(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ims__listarAmigos(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ims__logout(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ims__anadirAmigo(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ims__tratarSolicitud(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ims__listarPendientes(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ims__enviarMensaje(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ims__recibirMensajes(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ims__mensajesRecibidos(struct soap*);

/******************************************************************************\
 *                                                                            *
 * Client-Side Call Stubs                                                     *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 soap_call_ims__login(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *login, int *result);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ims__darAltaUsuario(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *login, int *result);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ims__darBajaUsuario(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *login, char *user, int *result);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ims__listarAmigos(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *login, int *result, struct ListaUsuarios *listaAmigos);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ims__logout(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *login, int *result);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ims__anadirAmigo(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *login, char *destino, int *result);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ims__tratarSolicitud(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *login, char *solicitante, int *result);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ims__listarPendientes(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *login, int *result, struct ListaUsuarios *listaAmigos);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ims__enviarMensaje(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *login, char *destino, char *msg, int *resul);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ims__recibirMensajes(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *login, struct ListaMensajes *listaMsg);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ims__mensajesRecibidos(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *login, int *result);

#ifdef __cplusplus
}
#endif

#endif

/* End of soapStub.h */
