/* soapClient.c
   Generated by gSOAP 2.8.10 from ims.h

Copyright(C) 2000-2012, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
1) GPL or 2) Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"
#ifdef __cplusplus
extern "C" {
#endif

SOAP_SOURCE_STAMP("@(#) soapClient.c ver 2.8.10 2013-12-04 18:41:29 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_call_ims__login(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *login, int *result)
{	struct ims__login soap_tmp_ims__login;
	struct ims__loginResponse *soap_tmp_ims__loginResponse;
	soap->encodingStyle = NULL;
	soap_tmp_ims__login.login = login;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ims__login(soap, &soap_tmp_ims__login);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ims__login(soap, &soap_tmp_ims__login, "ims:login", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ims__login(soap, &soap_tmp_ims__login, "ims:login", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!result)
		return soap_closesock(soap);
	soap_default_int(soap, result);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_tmp_ims__loginResponse = soap_get_ims__loginResponse(soap, NULL, "ims:loginResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (result && soap_tmp_ims__loginResponse->result)
		*result = *soap_tmp_ims__loginResponse->result;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ims__darAltaUsuario(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *login, int *result)
{	struct ims__darAltaUsuario soap_tmp_ims__darAltaUsuario;
	struct ims__darAltaUsuarioResponse *soap_tmp_ims__darAltaUsuarioResponse;
	soap->encodingStyle = NULL;
	soap_tmp_ims__darAltaUsuario.login = login;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ims__darAltaUsuario(soap, &soap_tmp_ims__darAltaUsuario);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ims__darAltaUsuario(soap, &soap_tmp_ims__darAltaUsuario, "ims:darAltaUsuario", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ims__darAltaUsuario(soap, &soap_tmp_ims__darAltaUsuario, "ims:darAltaUsuario", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!result)
		return soap_closesock(soap);
	soap_default_int(soap, result);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_tmp_ims__darAltaUsuarioResponse = soap_get_ims__darAltaUsuarioResponse(soap, NULL, "ims:darAltaUsuarioResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (result && soap_tmp_ims__darAltaUsuarioResponse->result)
		*result = *soap_tmp_ims__darAltaUsuarioResponse->result;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ims__darBajaUsuario(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *login, char *user, int *result)
{	struct ims__darBajaUsuario soap_tmp_ims__darBajaUsuario;
	struct ims__darBajaUsuarioResponse *soap_tmp_ims__darBajaUsuarioResponse;
	soap->encodingStyle = NULL;
	soap_tmp_ims__darBajaUsuario.login = login;
	soap_tmp_ims__darBajaUsuario.user = user;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ims__darBajaUsuario(soap, &soap_tmp_ims__darBajaUsuario);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ims__darBajaUsuario(soap, &soap_tmp_ims__darBajaUsuario, "ims:darBajaUsuario", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ims__darBajaUsuario(soap, &soap_tmp_ims__darBajaUsuario, "ims:darBajaUsuario", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!result)
		return soap_closesock(soap);
	soap_default_int(soap, result);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_tmp_ims__darBajaUsuarioResponse = soap_get_ims__darBajaUsuarioResponse(soap, NULL, "ims:darBajaUsuarioResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (result && soap_tmp_ims__darBajaUsuarioResponse->result)
		*result = *soap_tmp_ims__darBajaUsuarioResponse->result;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ims__listarAmigos(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *login, int *result, struct ListaUsuarios *listaAmigos)
{	struct ims__listarAmigos soap_tmp_ims__listarAmigos;
	struct ims__listarAmigosResponse *soap_tmp_ims__listarAmigosResponse;
	soap->encodingStyle = NULL;
	soap_tmp_ims__listarAmigos.login = login;
	soap_tmp_ims__listarAmigos.result = result;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ims__listarAmigos(soap, &soap_tmp_ims__listarAmigos);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ims__listarAmigos(soap, &soap_tmp_ims__listarAmigos, "ims:listarAmigos", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ims__listarAmigos(soap, &soap_tmp_ims__listarAmigos, "ims:listarAmigos", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!listaAmigos)
		return soap_closesock(soap);
	soap_default_ListaUsuarios(soap, listaAmigos);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_tmp_ims__listarAmigosResponse = soap_get_ims__listarAmigosResponse(soap, NULL, "ims:listarAmigosResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (listaAmigos && soap_tmp_ims__listarAmigosResponse->listaAmigos)
		*listaAmigos = *soap_tmp_ims__listarAmigosResponse->listaAmigos;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ims__logout(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *login, int *result)
{	struct ims__logout soap_tmp_ims__logout;
	struct ims__logoutResponse *soap_tmp_ims__logoutResponse;
	soap->encodingStyle = NULL;
	soap_tmp_ims__logout.login = login;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ims__logout(soap, &soap_tmp_ims__logout);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ims__logout(soap, &soap_tmp_ims__logout, "ims:logout", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ims__logout(soap, &soap_tmp_ims__logout, "ims:logout", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!result)
		return soap_closesock(soap);
	soap_default_int(soap, result);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_tmp_ims__logoutResponse = soap_get_ims__logoutResponse(soap, NULL, "ims:logoutResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (result && soap_tmp_ims__logoutResponse->result)
		*result = *soap_tmp_ims__logoutResponse->result;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ims__anadirAmigo(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *login, char *destino, int *result)
{	struct ims__anadirAmigo soap_tmp_ims__anadirAmigo;
	struct ims__anadirAmigoResponse *soap_tmp_ims__anadirAmigoResponse;
	soap->encodingStyle = NULL;
	soap_tmp_ims__anadirAmigo.login = login;
	soap_tmp_ims__anadirAmigo.destino = destino;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ims__anadirAmigo(soap, &soap_tmp_ims__anadirAmigo);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ims__anadirAmigo(soap, &soap_tmp_ims__anadirAmigo, "ims:anadirAmigo", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ims__anadirAmigo(soap, &soap_tmp_ims__anadirAmigo, "ims:anadirAmigo", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!result)
		return soap_closesock(soap);
	soap_default_int(soap, result);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_tmp_ims__anadirAmigoResponse = soap_get_ims__anadirAmigoResponse(soap, NULL, "ims:anadirAmigoResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (result && soap_tmp_ims__anadirAmigoResponse->result)
		*result = *soap_tmp_ims__anadirAmigoResponse->result;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ims__tratarSolicitud(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *login, char *solicitante, int *result)
{	struct ims__tratarSolicitud soap_tmp_ims__tratarSolicitud;
	struct ims__tratarSolicitudResponse *soap_tmp_ims__tratarSolicitudResponse;
	soap->encodingStyle = NULL;
	soap_tmp_ims__tratarSolicitud.login = login;
	soap_tmp_ims__tratarSolicitud.solicitante = solicitante;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ims__tratarSolicitud(soap, &soap_tmp_ims__tratarSolicitud);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ims__tratarSolicitud(soap, &soap_tmp_ims__tratarSolicitud, "ims:tratarSolicitud", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ims__tratarSolicitud(soap, &soap_tmp_ims__tratarSolicitud, "ims:tratarSolicitud", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!result)
		return soap_closesock(soap);
	soap_default_int(soap, result);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_tmp_ims__tratarSolicitudResponse = soap_get_ims__tratarSolicitudResponse(soap, NULL, "ims:tratarSolicitudResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (result && soap_tmp_ims__tratarSolicitudResponse->result)
		*result = *soap_tmp_ims__tratarSolicitudResponse->result;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ims__listarPendientes(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *login, int *result, struct ListaUsuarios *listaAmigos)
{	struct ims__listarPendientes soap_tmp_ims__listarPendientes;
	struct ims__listarPendientesResponse *soap_tmp_ims__listarPendientesResponse;
	soap->encodingStyle = NULL;
	soap_tmp_ims__listarPendientes.login = login;
	soap_tmp_ims__listarPendientes.result = result;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ims__listarPendientes(soap, &soap_tmp_ims__listarPendientes);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ims__listarPendientes(soap, &soap_tmp_ims__listarPendientes, "ims:listarPendientes", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ims__listarPendientes(soap, &soap_tmp_ims__listarPendientes, "ims:listarPendientes", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!listaAmigos)
		return soap_closesock(soap);
	soap_default_ListaUsuarios(soap, listaAmigos);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_tmp_ims__listarPendientesResponse = soap_get_ims__listarPendientesResponse(soap, NULL, "ims:listarPendientesResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (listaAmigos && soap_tmp_ims__listarPendientesResponse->listaAmigos)
		*listaAmigos = *soap_tmp_ims__listarPendientesResponse->listaAmigos;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ims__enviarMensaje(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *login, char *destino, char *msg, int *resul)
{	struct ims__enviarMensaje soap_tmp_ims__enviarMensaje;
	struct ims__enviarMensajeResponse *soap_tmp_ims__enviarMensajeResponse;
	soap->encodingStyle = NULL;
	soap_tmp_ims__enviarMensaje.login = login;
	soap_tmp_ims__enviarMensaje.destino = destino;
	soap_tmp_ims__enviarMensaje.msg = msg;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ims__enviarMensaje(soap, &soap_tmp_ims__enviarMensaje);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ims__enviarMensaje(soap, &soap_tmp_ims__enviarMensaje, "ims:enviarMensaje", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ims__enviarMensaje(soap, &soap_tmp_ims__enviarMensaje, "ims:enviarMensaje", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!resul)
		return soap_closesock(soap);
	soap_default_int(soap, resul);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_tmp_ims__enviarMensajeResponse = soap_get_ims__enviarMensajeResponse(soap, NULL, "ims:enviarMensajeResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (resul && soap_tmp_ims__enviarMensajeResponse->resul)
		*resul = *soap_tmp_ims__enviarMensajeResponse->resul;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ims__recibirMensajes(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *login, struct ListaMensajes *listaMsg)
{	struct ims__recibirMensajes soap_tmp_ims__recibirMensajes;
	struct ims__recibirMensajesResponse *soap_tmp_ims__recibirMensajesResponse;
	soap->encodingStyle = NULL;
	soap_tmp_ims__recibirMensajes.login = login;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ims__recibirMensajes(soap, &soap_tmp_ims__recibirMensajes);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ims__recibirMensajes(soap, &soap_tmp_ims__recibirMensajes, "ims:recibirMensajes", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ims__recibirMensajes(soap, &soap_tmp_ims__recibirMensajes, "ims:recibirMensajes", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!listaMsg)
		return soap_closesock(soap);
	soap_default_ListaMensajes(soap, listaMsg);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_tmp_ims__recibirMensajesResponse = soap_get_ims__recibirMensajesResponse(soap, NULL, "ims:recibirMensajesResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (listaMsg && soap_tmp_ims__recibirMensajesResponse->listaMsg)
		*listaMsg = *soap_tmp_ims__recibirMensajesResponse->listaMsg;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ims__mensajesRecibidos(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *login, int *result)
{	struct ims__mensajesRecibidos soap_tmp_ims__mensajesRecibidos;
	struct ims__mensajesRecibidosResponse *soap_tmp_ims__mensajesRecibidosResponse;
	soap->encodingStyle = NULL;
	soap_tmp_ims__mensajesRecibidos.login = login;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ims__mensajesRecibidos(soap, &soap_tmp_ims__mensajesRecibidos);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ims__mensajesRecibidos(soap, &soap_tmp_ims__mensajesRecibidos, "ims:mensajesRecibidos", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ims__mensajesRecibidos(soap, &soap_tmp_ims__mensajesRecibidos, "ims:mensajesRecibidos", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!result)
		return soap_closesock(soap);
	soap_default_int(soap, result);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_tmp_ims__mensajesRecibidosResponse = soap_get_ims__mensajesRecibidosResponse(soap, NULL, "ims:mensajesRecibidosResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (result && soap_tmp_ims__mensajesRecibidosResponse->result)
		*result = *soap_tmp_ims__mensajesRecibidosResponse->result;
	return soap_closesock(soap);
}

#ifdef __cplusplus
}
#endif

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapClient.c */
