/* soapH.h
   Generated by gSOAP 2.8.10 from ims.h

Copyright(C) 2000-2012, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
1) GPL or 2) Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapH_H
#define soapH_H
#include "soapStub.h"
#ifdef __cplusplus
extern "C" {
#endif
#ifndef WITH_NOIDREF
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);
SOAP_FMAC3 void *SOAP_FMAC4 soap_getelement(struct soap*, int*);
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

#ifndef soap_write_byte
#define soap_write_byte(soap, data) ( soap_begin_send(soap) || soap_put_byte(soap, data, "byte", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);

#ifndef soap_read_byte
#define soap_read_byte(soap, data) ( soap_begin_recv(soap) || !soap_get_byte(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);

#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

#ifndef soap_write_int
#define soap_write_int(soap, data) ( soap_begin_send(soap) || soap_put_int(soap, data, "int", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);

#ifndef soap_read_int
#define soap_read_int(soap, data) ( soap_begin_recv(soap) || !soap_get_int(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (59)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);

#ifndef soap_write_SOAP_ENV__Fault
#define soap_write_SOAP_ENV__Fault(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Fault(soap, data), 0) || soap_put_SOAP_ENV__Fault(soap, data, "SOAP-ENV:Fault", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Fault
#define soap_read_SOAP_ENV__Fault(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Fault(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (58)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);

#ifndef soap_write_SOAP_ENV__Reason
#define soap_write_SOAP_ENV__Reason(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Reason(soap, data), 0) || soap_put_SOAP_ENV__Reason(soap, data, "SOAP-ENV:Reason", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Reason
#define soap_read_SOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (55)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);

#ifndef soap_write_SOAP_ENV__Detail
#define soap_write_SOAP_ENV__Detail(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Detail(soap, data), 0) || soap_put_SOAP_ENV__Detail(soap, data, "SOAP-ENV:Detail", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Detail
#define soap_read_SOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (53)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);

#ifndef soap_write_SOAP_ENV__Code
#define soap_write_SOAP_ENV__Code(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Code(soap, data), 0) || soap_put_SOAP_ENV__Code(soap, data, "SOAP-ENV:Code", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Code
#define soap_read_SOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (52)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);

#ifndef soap_write_SOAP_ENV__Header
#define soap_write_SOAP_ENV__Header(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Header(soap, data), 0) || soap_put_SOAP_ENV__Header(soap, data, "SOAP-ENV:Header", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Header
#define soap_read_SOAP_ENV__Header(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Header(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);

#endif

#ifndef SOAP_TYPE_ims__mensajesRecibidos
#define SOAP_TYPE_ims__mensajesRecibidos (51)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ims__mensajesRecibidos(struct soap*, struct ims__mensajesRecibidos *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ims__mensajesRecibidos(struct soap*, const struct ims__mensajesRecibidos *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ims__mensajesRecibidos(struct soap*, const char*, int, const struct ims__mensajesRecibidos *, const char*);
SOAP_FMAC3 struct ims__mensajesRecibidos * SOAP_FMAC4 soap_in_ims__mensajesRecibidos(struct soap*, const char*, struct ims__mensajesRecibidos *, const char*);

#ifndef soap_write_ims__mensajesRecibidos
#define soap_write_ims__mensajesRecibidos(soap, data) ( soap_begin_send(soap) || (soap_serialize_ims__mensajesRecibidos(soap, data), 0) || soap_put_ims__mensajesRecibidos(soap, data, "ims:mensajesRecibidos", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ims__mensajesRecibidos(struct soap*, const struct ims__mensajesRecibidos *, const char*, const char*);

#ifndef soap_read_ims__mensajesRecibidos
#define soap_read_ims__mensajesRecibidos(soap, data) ( soap_begin_recv(soap) || !soap_get_ims__mensajesRecibidos(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ims__mensajesRecibidos * SOAP_FMAC4 soap_get_ims__mensajesRecibidos(struct soap*, struct ims__mensajesRecibidos *, const char*, const char*);

#ifndef SOAP_TYPE_ims__mensajesRecibidosResponse
#define SOAP_TYPE_ims__mensajesRecibidosResponse (50)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ims__mensajesRecibidosResponse(struct soap*, struct ims__mensajesRecibidosResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ims__mensajesRecibidosResponse(struct soap*, const struct ims__mensajesRecibidosResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ims__mensajesRecibidosResponse(struct soap*, const char*, int, const struct ims__mensajesRecibidosResponse *, const char*);
SOAP_FMAC3 struct ims__mensajesRecibidosResponse * SOAP_FMAC4 soap_in_ims__mensajesRecibidosResponse(struct soap*, const char*, struct ims__mensajesRecibidosResponse *, const char*);

#ifndef soap_write_ims__mensajesRecibidosResponse
#define soap_write_ims__mensajesRecibidosResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_ims__mensajesRecibidosResponse(soap, data), 0) || soap_put_ims__mensajesRecibidosResponse(soap, data, "ims:mensajesRecibidosResponse", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ims__mensajesRecibidosResponse(struct soap*, const struct ims__mensajesRecibidosResponse *, const char*, const char*);

#ifndef soap_read_ims__mensajesRecibidosResponse
#define soap_read_ims__mensajesRecibidosResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ims__mensajesRecibidosResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ims__mensajesRecibidosResponse * SOAP_FMAC4 soap_get_ims__mensajesRecibidosResponse(struct soap*, struct ims__mensajesRecibidosResponse *, const char*, const char*);

#ifndef SOAP_TYPE_ims__recibirMensajes
#define SOAP_TYPE_ims__recibirMensajes (48)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ims__recibirMensajes(struct soap*, struct ims__recibirMensajes *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ims__recibirMensajes(struct soap*, const struct ims__recibirMensajes *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ims__recibirMensajes(struct soap*, const char*, int, const struct ims__recibirMensajes *, const char*);
SOAP_FMAC3 struct ims__recibirMensajes * SOAP_FMAC4 soap_in_ims__recibirMensajes(struct soap*, const char*, struct ims__recibirMensajes *, const char*);

#ifndef soap_write_ims__recibirMensajes
#define soap_write_ims__recibirMensajes(soap, data) ( soap_begin_send(soap) || (soap_serialize_ims__recibirMensajes(soap, data), 0) || soap_put_ims__recibirMensajes(soap, data, "ims:recibirMensajes", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ims__recibirMensajes(struct soap*, const struct ims__recibirMensajes *, const char*, const char*);

#ifndef soap_read_ims__recibirMensajes
#define soap_read_ims__recibirMensajes(soap, data) ( soap_begin_recv(soap) || !soap_get_ims__recibirMensajes(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ims__recibirMensajes * SOAP_FMAC4 soap_get_ims__recibirMensajes(struct soap*, struct ims__recibirMensajes *, const char*, const char*);

#ifndef SOAP_TYPE_ims__recibirMensajesResponse
#define SOAP_TYPE_ims__recibirMensajesResponse (47)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ims__recibirMensajesResponse(struct soap*, struct ims__recibirMensajesResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ims__recibirMensajesResponse(struct soap*, const struct ims__recibirMensajesResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ims__recibirMensajesResponse(struct soap*, const char*, int, const struct ims__recibirMensajesResponse *, const char*);
SOAP_FMAC3 struct ims__recibirMensajesResponse * SOAP_FMAC4 soap_in_ims__recibirMensajesResponse(struct soap*, const char*, struct ims__recibirMensajesResponse *, const char*);

#ifndef soap_write_ims__recibirMensajesResponse
#define soap_write_ims__recibirMensajesResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_ims__recibirMensajesResponse(soap, data), 0) || soap_put_ims__recibirMensajesResponse(soap, data, "ims:recibirMensajesResponse", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ims__recibirMensajesResponse(struct soap*, const struct ims__recibirMensajesResponse *, const char*, const char*);

#ifndef soap_read_ims__recibirMensajesResponse
#define soap_read_ims__recibirMensajesResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ims__recibirMensajesResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ims__recibirMensajesResponse * SOAP_FMAC4 soap_get_ims__recibirMensajesResponse(struct soap*, struct ims__recibirMensajesResponse *, const char*, const char*);

#ifndef SOAP_TYPE_ims__enviarMensaje
#define SOAP_TYPE_ims__enviarMensaje (44)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ims__enviarMensaje(struct soap*, struct ims__enviarMensaje *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ims__enviarMensaje(struct soap*, const struct ims__enviarMensaje *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ims__enviarMensaje(struct soap*, const char*, int, const struct ims__enviarMensaje *, const char*);
SOAP_FMAC3 struct ims__enviarMensaje * SOAP_FMAC4 soap_in_ims__enviarMensaje(struct soap*, const char*, struct ims__enviarMensaje *, const char*);

#ifndef soap_write_ims__enviarMensaje
#define soap_write_ims__enviarMensaje(soap, data) ( soap_begin_send(soap) || (soap_serialize_ims__enviarMensaje(soap, data), 0) || soap_put_ims__enviarMensaje(soap, data, "ims:enviarMensaje", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ims__enviarMensaje(struct soap*, const struct ims__enviarMensaje *, const char*, const char*);

#ifndef soap_read_ims__enviarMensaje
#define soap_read_ims__enviarMensaje(soap, data) ( soap_begin_recv(soap) || !soap_get_ims__enviarMensaje(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ims__enviarMensaje * SOAP_FMAC4 soap_get_ims__enviarMensaje(struct soap*, struct ims__enviarMensaje *, const char*, const char*);

#ifndef SOAP_TYPE_ims__enviarMensajeResponse
#define SOAP_TYPE_ims__enviarMensajeResponse (43)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ims__enviarMensajeResponse(struct soap*, struct ims__enviarMensajeResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ims__enviarMensajeResponse(struct soap*, const struct ims__enviarMensajeResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ims__enviarMensajeResponse(struct soap*, const char*, int, const struct ims__enviarMensajeResponse *, const char*);
SOAP_FMAC3 struct ims__enviarMensajeResponse * SOAP_FMAC4 soap_in_ims__enviarMensajeResponse(struct soap*, const char*, struct ims__enviarMensajeResponse *, const char*);

#ifndef soap_write_ims__enviarMensajeResponse
#define soap_write_ims__enviarMensajeResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_ims__enviarMensajeResponse(soap, data), 0) || soap_put_ims__enviarMensajeResponse(soap, data, "ims:enviarMensajeResponse", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ims__enviarMensajeResponse(struct soap*, const struct ims__enviarMensajeResponse *, const char*, const char*);

#ifndef soap_read_ims__enviarMensajeResponse
#define soap_read_ims__enviarMensajeResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ims__enviarMensajeResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ims__enviarMensajeResponse * SOAP_FMAC4 soap_get_ims__enviarMensajeResponse(struct soap*, struct ims__enviarMensajeResponse *, const char*, const char*);

#ifndef SOAP_TYPE_ims__listarPendientes
#define SOAP_TYPE_ims__listarPendientes (41)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ims__listarPendientes(struct soap*, struct ims__listarPendientes *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ims__listarPendientes(struct soap*, const struct ims__listarPendientes *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ims__listarPendientes(struct soap*, const char*, int, const struct ims__listarPendientes *, const char*);
SOAP_FMAC3 struct ims__listarPendientes * SOAP_FMAC4 soap_in_ims__listarPendientes(struct soap*, const char*, struct ims__listarPendientes *, const char*);

#ifndef soap_write_ims__listarPendientes
#define soap_write_ims__listarPendientes(soap, data) ( soap_begin_send(soap) || (soap_serialize_ims__listarPendientes(soap, data), 0) || soap_put_ims__listarPendientes(soap, data, "ims:listarPendientes", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ims__listarPendientes(struct soap*, const struct ims__listarPendientes *, const char*, const char*);

#ifndef soap_read_ims__listarPendientes
#define soap_read_ims__listarPendientes(soap, data) ( soap_begin_recv(soap) || !soap_get_ims__listarPendientes(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ims__listarPendientes * SOAP_FMAC4 soap_get_ims__listarPendientes(struct soap*, struct ims__listarPendientes *, const char*, const char*);

#ifndef SOAP_TYPE_ims__listarPendientesResponse
#define SOAP_TYPE_ims__listarPendientesResponse (40)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ims__listarPendientesResponse(struct soap*, struct ims__listarPendientesResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ims__listarPendientesResponse(struct soap*, const struct ims__listarPendientesResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ims__listarPendientesResponse(struct soap*, const char*, int, const struct ims__listarPendientesResponse *, const char*);
SOAP_FMAC3 struct ims__listarPendientesResponse * SOAP_FMAC4 soap_in_ims__listarPendientesResponse(struct soap*, const char*, struct ims__listarPendientesResponse *, const char*);

#ifndef soap_write_ims__listarPendientesResponse
#define soap_write_ims__listarPendientesResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_ims__listarPendientesResponse(soap, data), 0) || soap_put_ims__listarPendientesResponse(soap, data, "ims:listarPendientesResponse", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ims__listarPendientesResponse(struct soap*, const struct ims__listarPendientesResponse *, const char*, const char*);

#ifndef soap_read_ims__listarPendientesResponse
#define soap_read_ims__listarPendientesResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ims__listarPendientesResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ims__listarPendientesResponse * SOAP_FMAC4 soap_get_ims__listarPendientesResponse(struct soap*, struct ims__listarPendientesResponse *, const char*, const char*);

#ifndef SOAP_TYPE_ims__tratarSolicitud
#define SOAP_TYPE_ims__tratarSolicitud (38)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ims__tratarSolicitud(struct soap*, struct ims__tratarSolicitud *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ims__tratarSolicitud(struct soap*, const struct ims__tratarSolicitud *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ims__tratarSolicitud(struct soap*, const char*, int, const struct ims__tratarSolicitud *, const char*);
SOAP_FMAC3 struct ims__tratarSolicitud * SOAP_FMAC4 soap_in_ims__tratarSolicitud(struct soap*, const char*, struct ims__tratarSolicitud *, const char*);

#ifndef soap_write_ims__tratarSolicitud
#define soap_write_ims__tratarSolicitud(soap, data) ( soap_begin_send(soap) || (soap_serialize_ims__tratarSolicitud(soap, data), 0) || soap_put_ims__tratarSolicitud(soap, data, "ims:tratarSolicitud", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ims__tratarSolicitud(struct soap*, const struct ims__tratarSolicitud *, const char*, const char*);

#ifndef soap_read_ims__tratarSolicitud
#define soap_read_ims__tratarSolicitud(soap, data) ( soap_begin_recv(soap) || !soap_get_ims__tratarSolicitud(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ims__tratarSolicitud * SOAP_FMAC4 soap_get_ims__tratarSolicitud(struct soap*, struct ims__tratarSolicitud *, const char*, const char*);

#ifndef SOAP_TYPE_ims__tratarSolicitudResponse
#define SOAP_TYPE_ims__tratarSolicitudResponse (37)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ims__tratarSolicitudResponse(struct soap*, struct ims__tratarSolicitudResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ims__tratarSolicitudResponse(struct soap*, const struct ims__tratarSolicitudResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ims__tratarSolicitudResponse(struct soap*, const char*, int, const struct ims__tratarSolicitudResponse *, const char*);
SOAP_FMAC3 struct ims__tratarSolicitudResponse * SOAP_FMAC4 soap_in_ims__tratarSolicitudResponse(struct soap*, const char*, struct ims__tratarSolicitudResponse *, const char*);

#ifndef soap_write_ims__tratarSolicitudResponse
#define soap_write_ims__tratarSolicitudResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_ims__tratarSolicitudResponse(soap, data), 0) || soap_put_ims__tratarSolicitudResponse(soap, data, "ims:tratarSolicitudResponse", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ims__tratarSolicitudResponse(struct soap*, const struct ims__tratarSolicitudResponse *, const char*, const char*);

#ifndef soap_read_ims__tratarSolicitudResponse
#define soap_read_ims__tratarSolicitudResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ims__tratarSolicitudResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ims__tratarSolicitudResponse * SOAP_FMAC4 soap_get_ims__tratarSolicitudResponse(struct soap*, struct ims__tratarSolicitudResponse *, const char*, const char*);

#ifndef SOAP_TYPE_ims__anadirAmigo
#define SOAP_TYPE_ims__anadirAmigo (35)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ims__anadirAmigo(struct soap*, struct ims__anadirAmigo *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ims__anadirAmigo(struct soap*, const struct ims__anadirAmigo *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ims__anadirAmigo(struct soap*, const char*, int, const struct ims__anadirAmigo *, const char*);
SOAP_FMAC3 struct ims__anadirAmigo * SOAP_FMAC4 soap_in_ims__anadirAmigo(struct soap*, const char*, struct ims__anadirAmigo *, const char*);

#ifndef soap_write_ims__anadirAmigo
#define soap_write_ims__anadirAmigo(soap, data) ( soap_begin_send(soap) || (soap_serialize_ims__anadirAmigo(soap, data), 0) || soap_put_ims__anadirAmigo(soap, data, "ims:anadirAmigo", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ims__anadirAmigo(struct soap*, const struct ims__anadirAmigo *, const char*, const char*);

#ifndef soap_read_ims__anadirAmigo
#define soap_read_ims__anadirAmigo(soap, data) ( soap_begin_recv(soap) || !soap_get_ims__anadirAmigo(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ims__anadirAmigo * SOAP_FMAC4 soap_get_ims__anadirAmigo(struct soap*, struct ims__anadirAmigo *, const char*, const char*);

#ifndef SOAP_TYPE_ims__anadirAmigoResponse
#define SOAP_TYPE_ims__anadirAmigoResponse (34)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ims__anadirAmigoResponse(struct soap*, struct ims__anadirAmigoResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ims__anadirAmigoResponse(struct soap*, const struct ims__anadirAmigoResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ims__anadirAmigoResponse(struct soap*, const char*, int, const struct ims__anadirAmigoResponse *, const char*);
SOAP_FMAC3 struct ims__anadirAmigoResponse * SOAP_FMAC4 soap_in_ims__anadirAmigoResponse(struct soap*, const char*, struct ims__anadirAmigoResponse *, const char*);

#ifndef soap_write_ims__anadirAmigoResponse
#define soap_write_ims__anadirAmigoResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_ims__anadirAmigoResponse(soap, data), 0) || soap_put_ims__anadirAmigoResponse(soap, data, "ims:anadirAmigoResponse", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ims__anadirAmigoResponse(struct soap*, const struct ims__anadirAmigoResponse *, const char*, const char*);

#ifndef soap_read_ims__anadirAmigoResponse
#define soap_read_ims__anadirAmigoResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ims__anadirAmigoResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ims__anadirAmigoResponse * SOAP_FMAC4 soap_get_ims__anadirAmigoResponse(struct soap*, struct ims__anadirAmigoResponse *, const char*, const char*);

#ifndef SOAP_TYPE_ims__logout
#define SOAP_TYPE_ims__logout (32)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ims__logout(struct soap*, struct ims__logout *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ims__logout(struct soap*, const struct ims__logout *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ims__logout(struct soap*, const char*, int, const struct ims__logout *, const char*);
SOAP_FMAC3 struct ims__logout * SOAP_FMAC4 soap_in_ims__logout(struct soap*, const char*, struct ims__logout *, const char*);

#ifndef soap_write_ims__logout
#define soap_write_ims__logout(soap, data) ( soap_begin_send(soap) || (soap_serialize_ims__logout(soap, data), 0) || soap_put_ims__logout(soap, data, "ims:logout", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ims__logout(struct soap*, const struct ims__logout *, const char*, const char*);

#ifndef soap_read_ims__logout
#define soap_read_ims__logout(soap, data) ( soap_begin_recv(soap) || !soap_get_ims__logout(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ims__logout * SOAP_FMAC4 soap_get_ims__logout(struct soap*, struct ims__logout *, const char*, const char*);

#ifndef SOAP_TYPE_ims__logoutResponse
#define SOAP_TYPE_ims__logoutResponse (31)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ims__logoutResponse(struct soap*, struct ims__logoutResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ims__logoutResponse(struct soap*, const struct ims__logoutResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ims__logoutResponse(struct soap*, const char*, int, const struct ims__logoutResponse *, const char*);
SOAP_FMAC3 struct ims__logoutResponse * SOAP_FMAC4 soap_in_ims__logoutResponse(struct soap*, const char*, struct ims__logoutResponse *, const char*);

#ifndef soap_write_ims__logoutResponse
#define soap_write_ims__logoutResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_ims__logoutResponse(soap, data), 0) || soap_put_ims__logoutResponse(soap, data, "ims:logoutResponse", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ims__logoutResponse(struct soap*, const struct ims__logoutResponse *, const char*, const char*);

#ifndef soap_read_ims__logoutResponse
#define soap_read_ims__logoutResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ims__logoutResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ims__logoutResponse * SOAP_FMAC4 soap_get_ims__logoutResponse(struct soap*, struct ims__logoutResponse *, const char*, const char*);

#ifndef SOAP_TYPE_ims__listarAmigos
#define SOAP_TYPE_ims__listarAmigos (29)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ims__listarAmigos(struct soap*, struct ims__listarAmigos *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ims__listarAmigos(struct soap*, const struct ims__listarAmigos *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ims__listarAmigos(struct soap*, const char*, int, const struct ims__listarAmigos *, const char*);
SOAP_FMAC3 struct ims__listarAmigos * SOAP_FMAC4 soap_in_ims__listarAmigos(struct soap*, const char*, struct ims__listarAmigos *, const char*);

#ifndef soap_write_ims__listarAmigos
#define soap_write_ims__listarAmigos(soap, data) ( soap_begin_send(soap) || (soap_serialize_ims__listarAmigos(soap, data), 0) || soap_put_ims__listarAmigos(soap, data, "ims:listarAmigos", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ims__listarAmigos(struct soap*, const struct ims__listarAmigos *, const char*, const char*);

#ifndef soap_read_ims__listarAmigos
#define soap_read_ims__listarAmigos(soap, data) ( soap_begin_recv(soap) || !soap_get_ims__listarAmigos(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ims__listarAmigos * SOAP_FMAC4 soap_get_ims__listarAmigos(struct soap*, struct ims__listarAmigos *, const char*, const char*);

#ifndef SOAP_TYPE_ims__listarAmigosResponse
#define SOAP_TYPE_ims__listarAmigosResponse (28)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ims__listarAmigosResponse(struct soap*, struct ims__listarAmigosResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ims__listarAmigosResponse(struct soap*, const struct ims__listarAmigosResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ims__listarAmigosResponse(struct soap*, const char*, int, const struct ims__listarAmigosResponse *, const char*);
SOAP_FMAC3 struct ims__listarAmigosResponse * SOAP_FMAC4 soap_in_ims__listarAmigosResponse(struct soap*, const char*, struct ims__listarAmigosResponse *, const char*);

#ifndef soap_write_ims__listarAmigosResponse
#define soap_write_ims__listarAmigosResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_ims__listarAmigosResponse(soap, data), 0) || soap_put_ims__listarAmigosResponse(soap, data, "ims:listarAmigosResponse", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ims__listarAmigosResponse(struct soap*, const struct ims__listarAmigosResponse *, const char*, const char*);

#ifndef soap_read_ims__listarAmigosResponse
#define soap_read_ims__listarAmigosResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ims__listarAmigosResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ims__listarAmigosResponse * SOAP_FMAC4 soap_get_ims__listarAmigosResponse(struct soap*, struct ims__listarAmigosResponse *, const char*, const char*);

#ifndef SOAP_TYPE_ims__darBajaUsuario
#define SOAP_TYPE_ims__darBajaUsuario (25)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ims__darBajaUsuario(struct soap*, struct ims__darBajaUsuario *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ims__darBajaUsuario(struct soap*, const struct ims__darBajaUsuario *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ims__darBajaUsuario(struct soap*, const char*, int, const struct ims__darBajaUsuario *, const char*);
SOAP_FMAC3 struct ims__darBajaUsuario * SOAP_FMAC4 soap_in_ims__darBajaUsuario(struct soap*, const char*, struct ims__darBajaUsuario *, const char*);

#ifndef soap_write_ims__darBajaUsuario
#define soap_write_ims__darBajaUsuario(soap, data) ( soap_begin_send(soap) || (soap_serialize_ims__darBajaUsuario(soap, data), 0) || soap_put_ims__darBajaUsuario(soap, data, "ims:darBajaUsuario", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ims__darBajaUsuario(struct soap*, const struct ims__darBajaUsuario *, const char*, const char*);

#ifndef soap_read_ims__darBajaUsuario
#define soap_read_ims__darBajaUsuario(soap, data) ( soap_begin_recv(soap) || !soap_get_ims__darBajaUsuario(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ims__darBajaUsuario * SOAP_FMAC4 soap_get_ims__darBajaUsuario(struct soap*, struct ims__darBajaUsuario *, const char*, const char*);

#ifndef SOAP_TYPE_ims__darBajaUsuarioResponse
#define SOAP_TYPE_ims__darBajaUsuarioResponse (24)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ims__darBajaUsuarioResponse(struct soap*, struct ims__darBajaUsuarioResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ims__darBajaUsuarioResponse(struct soap*, const struct ims__darBajaUsuarioResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ims__darBajaUsuarioResponse(struct soap*, const char*, int, const struct ims__darBajaUsuarioResponse *, const char*);
SOAP_FMAC3 struct ims__darBajaUsuarioResponse * SOAP_FMAC4 soap_in_ims__darBajaUsuarioResponse(struct soap*, const char*, struct ims__darBajaUsuarioResponse *, const char*);

#ifndef soap_write_ims__darBajaUsuarioResponse
#define soap_write_ims__darBajaUsuarioResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_ims__darBajaUsuarioResponse(soap, data), 0) || soap_put_ims__darBajaUsuarioResponse(soap, data, "ims:darBajaUsuarioResponse", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ims__darBajaUsuarioResponse(struct soap*, const struct ims__darBajaUsuarioResponse *, const char*, const char*);

#ifndef soap_read_ims__darBajaUsuarioResponse
#define soap_read_ims__darBajaUsuarioResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ims__darBajaUsuarioResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ims__darBajaUsuarioResponse * SOAP_FMAC4 soap_get_ims__darBajaUsuarioResponse(struct soap*, struct ims__darBajaUsuarioResponse *, const char*, const char*);

#ifndef SOAP_TYPE_ims__darAltaUsuario
#define SOAP_TYPE_ims__darAltaUsuario (22)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ims__darAltaUsuario(struct soap*, struct ims__darAltaUsuario *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ims__darAltaUsuario(struct soap*, const struct ims__darAltaUsuario *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ims__darAltaUsuario(struct soap*, const char*, int, const struct ims__darAltaUsuario *, const char*);
SOAP_FMAC3 struct ims__darAltaUsuario * SOAP_FMAC4 soap_in_ims__darAltaUsuario(struct soap*, const char*, struct ims__darAltaUsuario *, const char*);

#ifndef soap_write_ims__darAltaUsuario
#define soap_write_ims__darAltaUsuario(soap, data) ( soap_begin_send(soap) || (soap_serialize_ims__darAltaUsuario(soap, data), 0) || soap_put_ims__darAltaUsuario(soap, data, "ims:darAltaUsuario", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ims__darAltaUsuario(struct soap*, const struct ims__darAltaUsuario *, const char*, const char*);

#ifndef soap_read_ims__darAltaUsuario
#define soap_read_ims__darAltaUsuario(soap, data) ( soap_begin_recv(soap) || !soap_get_ims__darAltaUsuario(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ims__darAltaUsuario * SOAP_FMAC4 soap_get_ims__darAltaUsuario(struct soap*, struct ims__darAltaUsuario *, const char*, const char*);

#ifndef SOAP_TYPE_ims__darAltaUsuarioResponse
#define SOAP_TYPE_ims__darAltaUsuarioResponse (21)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ims__darAltaUsuarioResponse(struct soap*, struct ims__darAltaUsuarioResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ims__darAltaUsuarioResponse(struct soap*, const struct ims__darAltaUsuarioResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ims__darAltaUsuarioResponse(struct soap*, const char*, int, const struct ims__darAltaUsuarioResponse *, const char*);
SOAP_FMAC3 struct ims__darAltaUsuarioResponse * SOAP_FMAC4 soap_in_ims__darAltaUsuarioResponse(struct soap*, const char*, struct ims__darAltaUsuarioResponse *, const char*);

#ifndef soap_write_ims__darAltaUsuarioResponse
#define soap_write_ims__darAltaUsuarioResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_ims__darAltaUsuarioResponse(soap, data), 0) || soap_put_ims__darAltaUsuarioResponse(soap, data, "ims:darAltaUsuarioResponse", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ims__darAltaUsuarioResponse(struct soap*, const struct ims__darAltaUsuarioResponse *, const char*, const char*);

#ifndef soap_read_ims__darAltaUsuarioResponse
#define soap_read_ims__darAltaUsuarioResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ims__darAltaUsuarioResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ims__darAltaUsuarioResponse * SOAP_FMAC4 soap_get_ims__darAltaUsuarioResponse(struct soap*, struct ims__darAltaUsuarioResponse *, const char*, const char*);

#ifndef SOAP_TYPE_ims__login
#define SOAP_TYPE_ims__login (19)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ims__login(struct soap*, struct ims__login *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ims__login(struct soap*, const struct ims__login *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ims__login(struct soap*, const char*, int, const struct ims__login *, const char*);
SOAP_FMAC3 struct ims__login * SOAP_FMAC4 soap_in_ims__login(struct soap*, const char*, struct ims__login *, const char*);

#ifndef soap_write_ims__login
#define soap_write_ims__login(soap, data) ( soap_begin_send(soap) || (soap_serialize_ims__login(soap, data), 0) || soap_put_ims__login(soap, data, "ims:login", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ims__login(struct soap*, const struct ims__login *, const char*, const char*);

#ifndef soap_read_ims__login
#define soap_read_ims__login(soap, data) ( soap_begin_recv(soap) || !soap_get_ims__login(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ims__login * SOAP_FMAC4 soap_get_ims__login(struct soap*, struct ims__login *, const char*, const char*);

#ifndef SOAP_TYPE_ims__loginResponse
#define SOAP_TYPE_ims__loginResponse (18)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ims__loginResponse(struct soap*, struct ims__loginResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ims__loginResponse(struct soap*, const struct ims__loginResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ims__loginResponse(struct soap*, const char*, int, const struct ims__loginResponse *, const char*);
SOAP_FMAC3 struct ims__loginResponse * SOAP_FMAC4 soap_in_ims__loginResponse(struct soap*, const char*, struct ims__loginResponse *, const char*);

#ifndef soap_write_ims__loginResponse
#define soap_write_ims__loginResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_ims__loginResponse(soap, data), 0) || soap_put_ims__loginResponse(soap, data, "ims:loginResponse", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ims__loginResponse(struct soap*, const struct ims__loginResponse *, const char*, const char*);

#ifndef soap_read_ims__loginResponse
#define soap_read_ims__loginResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ims__loginResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ims__loginResponse * SOAP_FMAC4 soap_get_ims__loginResponse(struct soap*, struct ims__loginResponse *, const char*, const char*);

#ifndef SOAP_TYPE_ListaMensajes
#define SOAP_TYPE_ListaMensajes (14)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ListaMensajes(struct soap*, struct ListaMensajes *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ListaMensajes(struct soap*, const struct ListaMensajes *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ListaMensajes(struct soap*, const char*, int, const struct ListaMensajes *, const char*);
SOAP_FMAC3 struct ListaMensajes * SOAP_FMAC4 soap_in_ListaMensajes(struct soap*, const char*, struct ListaMensajes *, const char*);

#ifndef soap_write_ListaMensajes
#define soap_write_ListaMensajes(soap, data) ( soap_begin_send(soap) || (soap_serialize_ListaMensajes(soap, data), 0) || soap_put_ListaMensajes(soap, data, "ListaMensajes", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ListaMensajes(struct soap*, const struct ListaMensajes *, const char*, const char*);

#ifndef soap_read_ListaMensajes
#define soap_read_ListaMensajes(soap, data) ( soap_begin_recv(soap) || !soap_get_ListaMensajes(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ListaMensajes * SOAP_FMAC4 soap_get_ListaMensajes(struct soap*, struct ListaMensajes *, const char*, const char*);

#ifndef SOAP_TYPE_ListaUsuarios
#define SOAP_TYPE_ListaUsuarios (12)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ListaUsuarios(struct soap*, struct ListaUsuarios *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ListaUsuarios(struct soap*, const struct ListaUsuarios *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ListaUsuarios(struct soap*, const char*, int, const struct ListaUsuarios *, const char*);
SOAP_FMAC3 struct ListaUsuarios * SOAP_FMAC4 soap_in_ListaUsuarios(struct soap*, const char*, struct ListaUsuarios *, const char*);

#ifndef soap_write_ListaUsuarios
#define soap_write_ListaUsuarios(soap, data) ( soap_begin_send(soap) || (soap_serialize_ListaUsuarios(soap, data), 0) || soap_put_ListaUsuarios(soap, data, "ListaUsuarios", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ListaUsuarios(struct soap*, const struct ListaUsuarios *, const char*, const char*);

#ifndef soap_read_ListaUsuarios
#define soap_read_ListaUsuarios(soap, data) ( soap_begin_recv(soap) || !soap_get_ListaUsuarios(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ListaUsuarios * SOAP_FMAC4 soap_get_ListaUsuarios(struct soap*, struct ListaUsuarios *, const char*, const char*);

#ifndef SOAP_TYPE_User
#define SOAP_TYPE_User (11)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_User(struct soap*, struct User *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_User(struct soap*, const struct User *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_User(struct soap*, const char*, int, const struct User *, const char*);
SOAP_FMAC3 struct User * SOAP_FMAC4 soap_in_User(struct soap*, const char*, struct User *, const char*);

#ifndef soap_write_User
#define soap_write_User(soap, data) ( soap_begin_send(soap) || (soap_serialize_User(soap, data), 0) || soap_put_User(soap, data, "User", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_User(struct soap*, const struct User *, const char*, const char*);

#ifndef soap_read_User
#define soap_read_User(soap, data) ( soap_begin_recv(soap) || !soap_get_User(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct User * SOAP_FMAC4 soap_get_User(struct soap*, struct User *, const char*, const char*);

#ifndef SOAP_TYPE_Message
#define SOAP_TYPE_Message (8)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_Message(struct soap*, struct Message *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_Message(struct soap*, const struct Message *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_Message(struct soap*, const char*, int, const struct Message *, const char*);
SOAP_FMAC3 struct Message * SOAP_FMAC4 soap_in_Message(struct soap*, const char*, struct Message *, const char*);

#ifndef soap_write_Message
#define soap_write_Message(soap, data) ( soap_begin_send(soap) || (soap_serialize_Message(soap, data), 0) || soap_put_Message(soap, data, "Message", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_Message(struct soap*, const struct Message *, const char*, const char*);

#ifndef soap_read_Message
#define soap_read_Message(soap, data) ( soap_begin_recv(soap) || !soap_get_Message(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct Message * SOAP_FMAC4 soap_get_Message(struct soap*, struct Message *, const char*, const char*);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (61)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Reason
#define soap_write_PointerToSOAP_ENV__Reason(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Reason(soap, data), 0) || soap_put_PointerToSOAP_ENV__Reason(soap, data, "SOAP-ENV:Reason", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Reason
#define soap_read_PointerToSOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (60)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Detail
#define soap_write_PointerToSOAP_ENV__Detail(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Detail(soap, data), 0) || soap_put_PointerToSOAP_ENV__Detail(soap, data, "SOAP-ENV:Detail", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Detail
#define soap_read_PointerToSOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (54)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Code
#define soap_write_PointerToSOAP_ENV__Code(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Code(soap, data), 0) || soap_put_PointerToSOAP_ENV__Code(soap, data, "SOAP-ENV:Code", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Code
#define soap_read_PointerToSOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);

#endif

#ifndef SOAP_TYPE_PointerToListaMensajes
#define SOAP_TYPE_PointerToListaMensajes (45)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToListaMensajes(struct soap*, struct ListaMensajes *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToListaMensajes(struct soap*, const char *, int, struct ListaMensajes *const*, const char *);
SOAP_FMAC3 struct ListaMensajes ** SOAP_FMAC4 soap_in_PointerToListaMensajes(struct soap*, const char*, struct ListaMensajes **, const char*);

#ifndef soap_write_PointerToListaMensajes
#define soap_write_PointerToListaMensajes(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToListaMensajes(soap, data), 0) || soap_put_PointerToListaMensajes(soap, data, "ListaMensajes", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToListaMensajes(struct soap*, struct ListaMensajes *const*, const char*, const char*);

#ifndef soap_read_PointerToListaMensajes
#define soap_read_PointerToListaMensajes(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToListaMensajes(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ListaMensajes ** SOAP_FMAC4 soap_get_PointerToListaMensajes(struct soap*, struct ListaMensajes **, const char*, const char*);

#ifndef SOAP_TYPE_PointerToListaUsuarios
#define SOAP_TYPE_PointerToListaUsuarios (26)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToListaUsuarios(struct soap*, struct ListaUsuarios *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToListaUsuarios(struct soap*, const char *, int, struct ListaUsuarios *const*, const char *);
SOAP_FMAC3 struct ListaUsuarios ** SOAP_FMAC4 soap_in_PointerToListaUsuarios(struct soap*, const char*, struct ListaUsuarios **, const char*);

#ifndef soap_write_PointerToListaUsuarios
#define soap_write_PointerToListaUsuarios(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToListaUsuarios(soap, data), 0) || soap_put_PointerToListaUsuarios(soap, data, "ListaUsuarios", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToListaUsuarios(struct soap*, struct ListaUsuarios *const*, const char*, const char*);

#ifndef soap_read_PointerToListaUsuarios
#define soap_read_PointerToListaUsuarios(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToListaUsuarios(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ListaUsuarios ** SOAP_FMAC4 soap_get_PointerToListaUsuarios(struct soap*, struct ListaUsuarios **, const char*, const char*);

#ifndef SOAP_TYPE_PointerToint
#define SOAP_TYPE_PointerToint (16)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToint(struct soap*, int *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToint(struct soap*, const char *, int, int *const*, const char *);
SOAP_FMAC3 int ** SOAP_FMAC4 soap_in_PointerToint(struct soap*, const char*, int **, const char*);

#ifndef soap_write_PointerToint
#define soap_write_PointerToint(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToint(soap, data), 0) || soap_put_PointerToint(soap, data, "int", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToint(struct soap*, int *const*, const char*, const char*);

#ifndef soap_read_PointerToint
#define soap_read_PointerToint(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToint(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 int ** SOAP_FMAC4 soap_get_PointerToint(struct soap*, int **, const char*, const char*);

#ifndef SOAP_TYPE_xsd__string
#define SOAP_TYPE_xsd__string (7)
#endif

#define soap_default_xsd__string(soap, a) soap_default_string(soap, a)


#define soap_serialize_xsd__string(soap, a) soap_serialize_string(soap, a)

SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_xsd__string(struct soap*, const char*, char **, const char*);

#ifndef soap_write_xsd__string
#define soap_write_xsd__string(soap, data) ( soap_begin_send(soap) || (soap_serialize_xsd__string(soap, data), 0) || soap_put_xsd__string(soap, data, "byte", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__string(struct soap*, char *const*, const char*, const char*);

#ifndef soap_read_xsd__string
#define soap_read_xsd__string(soap, data) ( soap_begin_recv(soap) || !soap_get_xsd__string(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_xsd__string(struct soap*, char **, const char*, const char*);

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif

#define soap_default__QName(soap, a) soap_default_string(soap, a)


#define soap_serialize__QName(soap, a) soap_serialize_string(soap, a)

SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);

#ifndef soap_write__QName
#define soap_write__QName(soap, data) ( soap_begin_send(soap) || (soap_serialize__QName(soap, data), 0) || soap_put__QName(soap, data, "byte", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);

#ifndef soap_read__QName
#define soap_read__QName(soap, data) ( soap_begin_recv(soap) || !soap_get__QName(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);

#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (4)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);

#ifndef soap_write_string
#define soap_write_string(soap, data) ( soap_begin_send(soap) || (soap_serialize_string(soap, data), 0) || soap_put_string(soap, data, "byte", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);

#ifndef soap_read_string
#define soap_read_string(soap, data) ( soap_begin_recv(soap) || !soap_get_string(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);

#ifndef SOAP_TYPE_Array100OfMessage
#define SOAP_TYPE_Array100OfMessage (15)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_Array100OfMessage(struct soap*, struct Message[100]);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_Array100OfMessage(struct soap*, struct Message const[100]);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_Array100OfMessage(struct soap*, const char*, int, struct Message const[100], const char*);
SOAP_FMAC3 struct Message * SOAP_FMAC4 soap_in_Array100OfMessage(struct soap*, const char*, struct Message[100], const char*);

#ifndef soap_write_Array100OfMessage
#define soap_write_Array100OfMessage(soap, data) ( soap_begin_send(soap) || (soap_serialize_Array100OfMessage(soap, data), 0) || soap_put_Array100OfMessage(soap, data, "SOAP-ENC:Array", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_Array100OfMessage(struct soap*, struct Message const[100], const char*, const char*);

#ifndef soap_read_Array100OfMessage
#define soap_read_Array100OfMessage(soap, data) ( soap_begin_recv(soap) || !soap_get_Array100OfMessage(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct Message * SOAP_FMAC4 soap_get_Array100OfMessage(struct soap*, struct Message[100], const char*, const char*);

#ifndef SOAP_TYPE_Array50OfUser
#define SOAP_TYPE_Array50OfUser (13)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_Array50OfUser(struct soap*, struct User[50]);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_Array50OfUser(struct soap*, struct User const[50]);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_Array50OfUser(struct soap*, const char*, int, struct User const[50], const char*);
SOAP_FMAC3 struct User * SOAP_FMAC4 soap_in_Array50OfUser(struct soap*, const char*, struct User[50], const char*);

#ifndef soap_write_Array50OfUser
#define soap_write_Array50OfUser(soap, data) ( soap_begin_send(soap) || (soap_serialize_Array50OfUser(soap, data), 0) || soap_put_Array50OfUser(soap, data, "SOAP-ENC:Array", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_Array50OfUser(struct soap*, struct User const[50], const char*, const char*);

#ifndef soap_read_Array50OfUser
#define soap_read_Array50OfUser(soap, data) ( soap_begin_recv(soap) || !soap_get_Array50OfUser(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct User * SOAP_FMAC4 soap_get_Array50OfUser(struct soap*, struct User[50], const char*, const char*);

#ifndef SOAP_TYPE_Array144Ofbyte
#define SOAP_TYPE_Array144Ofbyte (10)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_Array144Ofbyte(struct soap*, char[144]);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_Array144Ofbyte(struct soap*, char const[144]);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_Array144Ofbyte(struct soap*, const char*, int, char const[144], const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_Array144Ofbyte(struct soap*, const char*, char[144], const char*);

#ifndef soap_write_Array144Ofbyte
#define soap_write_Array144Ofbyte(soap, data) ( soap_begin_send(soap) || (soap_serialize_Array144Ofbyte(soap, data), 0) || soap_put_Array144Ofbyte(soap, data, "SOAP-ENC:Array", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_Array144Ofbyte(struct soap*, char const[144], const char*, const char*);

#ifndef soap_read_Array144Ofbyte
#define soap_read_Array144Ofbyte(soap, data) ( soap_begin_recv(soap) || !soap_get_Array144Ofbyte(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 char * SOAP_FMAC4 soap_get_Array144Ofbyte(struct soap*, char[144], const char*, const char*);

#ifndef SOAP_TYPE_Array20Ofbyte
#define SOAP_TYPE_Array20Ofbyte (9)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_Array20Ofbyte(struct soap*, char[20]);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_Array20Ofbyte(struct soap*, char const[20]);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_Array20Ofbyte(struct soap*, const char*, int, char const[20], const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_Array20Ofbyte(struct soap*, const char*, char[20], const char*);

#ifndef soap_write_Array20Ofbyte
#define soap_write_Array20Ofbyte(soap, data) ( soap_begin_send(soap) || (soap_serialize_Array20Ofbyte(soap, data), 0) || soap_put_Array20Ofbyte(soap, data, "SOAP-ENC:Array", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_Array20Ofbyte(struct soap*, char const[20], const char*, const char*);

#ifndef soap_read_Array20Ofbyte
#define soap_read_Array20Ofbyte(soap, data) ( soap_begin_recv(soap) || !soap_get_Array20Ofbyte(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 char * SOAP_FMAC4 soap_get_Array20Ofbyte(struct soap*, char[20], const char*, const char*);

#ifdef __cplusplus
}
#endif

#endif

/* End of soapH.h */
